name: Modrinth Publish
description: A GitHub workflow for publishing plugin versions to Modrinth
inputs:
  token:
    required: true
    description: Modrinth API token
  project:
    required: true
    description: Modrinth project ID
  file:
    required: true
    description: Path to file to upload
  changelog:
    required: false
    description: The changelog for this version (markdown). Defaults to GitHub release notes.
  loaders:
    required: true
    description: The mod loaders that this version supports (separated by commas or as JSON string array). See [createVersion](https://docs.modrinth.com/api-spec#tag/versions/operation/createVersion)
  dependencies:
    required: false
    description: A list of specific versions of projects that this version depends on (as JSON array). See [createVersion](https://docs.modrinth.com/api-spec#tag/versions/operation/createVersion)
    default: "[]"
  api-domain:
    required: false
    description: Modrinth API domain. For testing purposes you can set this to `staging-api.modrinth.com`. See [Modrinth Staging Server](https://staging.modrinth.com)
    default: "api.modrinth.com"
outputs:
  version-id:
    description: Version ID generated by Modrinth
  version-url:
    description: URL to the version's page on Modrinth
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: green
