name: Modrinth Publish
description: Publish a version on Modrinth
inputs:
  api-domain:
    required: false
    description: Modrinth API domain.
    default: api.modrinth.com
    deprecationMessage: >
      The Modrinth Staging API is no longer recommended for testing or as a sandbox. Instead, consider creating a
      ‘draft’ project on the production API and deleting it after testing. This input is scheduled for removal in
      `v3.0.0`.
  token:
    required: true
    description: Modrinth API token.
  project:
    required: true
    description: The ID of the project this version is for.
  name:
    required: false
    description: The name of this version.
  version:
    required: true
    description: The version number. Ideally will follow semantic versioning.
  channel:
    required: false
    description: The release channel for this version (`release`, `beta`, or `alpha`). If not specified, will be inferred from the version number (based on whether it contains `alpha`, `beta`, `rc`, `pre`).
  featured:
    required: false
    description: Whether the version is featured or not. If not set, defaults to `true` if the release channel is `release`, otherwise `false`.
  changelog:
    required: false
    description: The changelog for this version.
  loaders:
    required: true
    description: The mod loaders that this version supports, separated by new line, or as JSON string array. In case of resource packs, use `minecraft`.
  game-versions:
    required: false
    description: A list of versions of Minecraft that this version supports, separated by new line, or as JSON string array. You can also use e.g. `1.20.x`, `1.21.x`, ….
    default: "[]"
  files:
    required: true
    description: A list of file paths to upload, separated by new line, or as JSON string array. There must be at least one file, unless the new version’s status is `draft`. The allowed file extensions are `.mrpack`, `.jar`, `.zip`, and `.litemod`.
  primary-file:
    required: false
    description: The name (not path) from `files` to be set as the primary file.
  dependencies:
    required: false
    description: A list of specific versions of projects that this version depends on, formatted as JSON array. See [Create Version - Modrinth API docs](https://docs.modrinth.com/api/operations/createversion/#request-body).
    default: "[]"
  status:
    required: false
    description: Allowed values are `listed`, `archived`, `draft`, `unlisted`, `scheduled`, `unknown`.
    default: "listed"
  requested-status:
    required: false
    description: Allowed values are `listed`, `archived`, `draft`, `unlisted`.
outputs:
  version-id:
    description: Version ID generated by Modrinth.
runs:
  using: docker
  image: docker://ghcr.io/cloudnode-pro/modrinth-publish:2.1.2
  env:
    GH_INPUTS: ${{ toJSON(inputs) }}
branding:
  icon: upload-cloud
  color: green
